[project]
name = "chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "azure-identity>=1.25.0",
    "fastapi>=0.117.1",
    "openai[azure]>=1.109.1",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.37.0",
]
